jasp-stats/jaspAudit

R/auditCommonFunctions.R, inst/qml/auditBayesianPlanning.qml, inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalPlanning.qml, inst/qml/auditClassicalWorkflow.qml
@boutinb After this is merged into the module here, I will make sure to make a PR to stable to also include these changes there.
=> Insert audit hotfix and change some decimal places to 2

R/auditCommonFunctions.R, inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalWorkflow.qml, inst/qml/auditSelection.qml
- Fixed an error with a no-show message
- Allow the user to specify the starting point inside the selection interval
PR to `stable` branch: https://github.com/jasp-stats/jasp-desktop/pull/4073
=> Some changes to the selection analyses

R/auditCommonFunctions.R, inst/qml/auditBayesianEvaluation.qml, inst/qml/auditClassicalEvaluation.qml
Fix https://github.com/jasp-stats/jasp-test-release/issues/819
Fix https://github.com/jasp-stats/jasp-test-release/issues/841
=> Update fixes for release

R/auditCommonFunctions.R
Fix issues in https://github.com/jasp-stats/jasp-test-release/issues/874
=> Fix issues for release #2

inst/qml/auditBayesianEvaluation.qml, inst/qml/auditBayesianPlanning.qml, inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalWorkflow.qml, inst/qml/auditSelection.qml
Hopefully closes https://github.com/jasp-stats/jasp-issues/issues/1119
=> Remove Items and Gridlayouts from the qml to fix linux crash

R/auditCommonFunctions.R, inst/qml/auditClassicalWorkflow.qml
+ Import JASP in qml to make sure that the tableView shows correctly.
+ Make sure that the minimum precision is recognized as a value in the evaluation stage
+ Change option name in the classical workflow to be consistent with the rest
=> Some bug fixes for workflows

inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalWorkflow.qml
When this is merged we can hopefully close https://github.com/jasp-stats/jasp-issues/issues/1139
=> Add initialized if-statement to qml forms

inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalWorkflow.qml
Close https://github.com/jasp-stats/INTERNAL-jasp/issues/1291
=> Adjust decimals in tableview to 10

inst/qml/auditBayesianEvaluation.qml, inst/qml/auditBayesianPlanning.qml, inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalEvaluation.qml, inst/qml/auditClassicalPlanning.qml, inst/qml/auditClassicalWorkflow.qml, inst/qml/auditSelection.qml
=> Turn & into &&

R/auditClassicalBenfordsLaw.R, R/auditClassicalNumberBunching.R
Should close https://github.com/jasp-stats/INTERNAL-jasp/issues/1407
=> Fix https://github.com/jasp-stats/INTERNAL-jasp/issues/1407

DESCRIPTION, README.md
=> Add DOI for paper

R/auditCommonFunctions.R, inst/Description.qml, inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalWorkflow.qml, inst/qml/auditSelection.qml
Feedback from in-class testing @ nyenrode
=> Make seed "global" for all methods and place it more prominent

DESCRIPTION, R/auditCommonFunctions.R, README.md, inst/qml/auditBayesianPlanning.qml, inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalPlanning.qml, inst/qml/auditClassicalWorkflow.qml, tests/testthat/_snaps/auditbayesianevaluation/evaluation-of-sampling-objectives-1.svg, tests/testthat/_snaps/auditbayesianevaluation/evaluation-of-sampling-objectives-2.svg, tests/testthat/_snaps/auditbayesianevaluation/evaluation-of-sampling-objectives-3.svg, tests/testthat/_snaps/auditbayesianworkflow/evaluation-of-sampling-objectives.svg, tests/testthat/_snaps/auditclassicalevaluation/evaluation-of-sampling-objectives-1.svg, tests/testthat/_snaps/auditclassicalevaluation/evaluation-of-sampling-objectives-2.svg, tests/testthat/_snaps/auditclassicalevaluation/evaluation-of-sampling-objectives-3.svg, tests/testthat/_snaps/auditclassicalworkflow/evaluation-of-sampling-objectives.svg
- Closes https://github.com/jasp-stats/jasp-test-release/issues/1690
- Closes https://github.com/jasp-stats/jasp-test-release/issues/1707
- Closes https://github.com/jasp-stats/jasp-test-release/issues/1693
=> Fix typo in error message and cropped plot

R/auditCommonFunctions.R
Without this fix the table shows like this:
=> Make sample table work with translated versions

R/auditCommonFunctionsBayesian.R
- Closes https://github.com/jasp-stats/jasp-test-release/issues/2194
=> Bug fixes for 0.17

inst/Upgrades.qml
Otherwise the data library jasp file will not refresh appropriately
=> Add missing Upgrades.qml file for 0.17.2

R/auditCommonFunctions.R
This PR ensures that an error is projected on the screen when using the partial projection method and the sample size exceeds the maximum specified by the user.
=> Fix sample size error not displayed for partial projection

R/auditCommonFunctions.R
Add an error message for the case in https://github.com/jasp-stats/jasp-test-release/issues/2363
=> Add error message for attribute sampling edge case

inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalWorkflow.qml
Closes https://github.com/jasp-stats/jasp-test-release/issues/2369
=> Fix https://github.com/jasp-stats/jasp-test-release/issues/2369

R/auditClassicalModelFairness.R, inst/help/auditClassicalBenfordsLaw.md, inst/help/auditClassicalBenfordsLaw_nl.md, inst/help/auditClassicalModelFairness.md, inst/help/auditClassicalModelFairness_nl.md, inst/qml/auditClassicalModelFairness.qml, tests/testthat/test-auditclassicalmodelfairness.R
- Add forgotten help files
- Add forgotten gettexts
- Add forgotten qml id
- Some fixes to table
=> Some small fixes

R/auditCommonFunctions.R, README.md
Closes https://github.com/jasp-stats/jasp-test-release/issues/2465#event-11023308528
=> Add blogpost link to readme and fix issue in evaluation

inst/qml/auditBayesianWorkflow.qml, inst/qml/auditClassicalWorkflow.qml, inst/qml/common/planning/PriorMethod.qml
Closes https://github.com/jasp-stats/INTERNAL-jasp/issues/2517
=> Put back scrolling in audit workflow data viewer

inst/qml/auditClassicalBenfordsLaw.qml, inst/qml/auditClassicalEstimation.qml, inst/qml/auditClassicalModelFairness.qml, inst/qml/auditClassicalNumberBunching.qml, inst/qml/common/evaluation/EvaluationVariablesList.qml, inst/qml/common/selection/BookVariable.qml, inst/qml/common/selection/RankVariable.qml
These are changes I could easily spot. I am not ruling out that more will follow after testing.
=> Changes related to new variable conversion

R/auditCommonFunctions.R
- Closes https://github.com/jasp-stats/jasp-test-release/issues/2750
=> Add error message for invalid value of absolute materiality

R/auditCommonFunctions.R
These are statics numbers which will never change.
=> Never show decimals in arm table

R/auditCommonFunctions.R
Fix the names of some dependencies
=> Fix dependencies

R/auditBayesianEvaluation.R, tests/testthat/_snaps/auditbayesianevaluation/sequential-analysis-1.svg, tests/testthat/_snaps/auditbayesianevaluation/sequential-analysis-2.svg, tests/testthat/test-auditbayesianevaluation.R
Adds a unit test for the sequential analysis plot in the Bayesian evaluation analysis.
=> Add unit test for sequential analysis plot

R/auditCommonFunctions.R, R/auditCommonFunctionsBayesian.R
Add explanation for hypotheses BF+- vs. BF10
=> Fix BF_10 vs. BF_+-
